apiVersion: apps/v1
kind: Deployment
metadata:
  name: datahub
  namespace: datahub
  labels:
    app: datahub
spec:
  replicas: 2

  selector:
    matchLabels:
      app: datahub

  template:
    metadata:
      labels:
        app: datahub

    spec:
      containers:
        - name: datahub

          image: jibachh/datahub:v1

          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8080

          env:
            - name: PORT
              value: "8080"

            - name: DATABASE
              value: "/data/data.db"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /healthz
              port: http

            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: http

            initialDelaySeconds: 15
            periodSeconds: 20

          volumeMounts:
            - name: data
              mountPath: /data

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: datahub-pvc
