apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-alpine
  namespace: broadway
spec:
  replicas: 1
  selector:
    matchLabels:
      resource: pod-alpine

  template:
    metadata:
      name: pod-alpine
      labels:
        resource: pod-alpine

    spec:
      containers:
        - name: alpine
          image: jibachh/alpine:3.23.4

          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "10Mi"
              cpu: "1m"

          volumeMounts:
            - name: alpine-config-vol
              mountPath: /etc/config/
          envFrom:
            - configMapRef:
                name: alpine-config-env
            - secretRef:
                name: alpine-secret
      volumes:
        - name: alpine-config-vol
          configMap:
            name: alpine-config
